apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # initContainers:
      #   - name: fetch-dump
      #     image: google/cloud-sdk:slim
      #     command: ["/bin/sh", "-c"]
      #     args:
      #       - gsutil cp gs://db-restore-bucket-gbure-2025/it2025.dump /docker-entrypoint-initdb.d/it2025.dump
      #     volumeMounts:
      #       - name: dump-volume
      #         mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: postgres
          image: postgres:17.5
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
            # - name: dump-volume
            #   mountPath: /docker-entrypoint-initdb.d/it2025.dump
            #   subPath: it2025.dump
            - name: setup-script-volume
              mountPath: /docker-entrypoint-initdb.d/setup.sh
              subPath: setup.sh
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: dump-volume
          emptyDir: {}
        - name: setup-script-volume
          configMap:
            name: setup-script
